name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
    - name: Install musl-tools
      run: sudo apt-get install -y musl-tools
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl --verbose
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: crust-linux-x86_64
        path: target/x86_64-unknown-linux-musl/release/crust
        
  build-linux-aarch64:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target aarch64-unknown-linux-musl --verbose
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: crust-linux-aarch64
        path: target/aarch64-unknown-linux-musl/release/crust
